---
- name: Provision VM
  hosts: all
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    docker_users: bxz
    terraform_version: 0.12.20
  roles:
    - packages
    - sshd
    - docker
    - fail2ban
    - terraform
