---
- name: Update repositories and packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-nox
    - git
    - htop
    - iotop
    - iftop
    - glances
    - tree
    - tmux
    - curl
    - nmap
    - whois
    - python3
    - python3-pip
    - python-flake8
    - python3-venv
    - apt-transport-https
    - software-properties-common
    - gnupg-agent
    - ca-certificates
