---
- name: install fail2ban
  apt:
    name: fail2ban
    state: latest

- name: copy fail2ban template 
  template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.local
  notify:
    - restart fail2ban
